-- TrillFlow Project Workspace: project-owned files and optional start dates.
-- Apply this in Supabase SQL Editor before deploying the matching application code.

alter table public.projects
    add column if not exists start_date date;

create table if not exists public.project_files (
    id bigint generated by default as identity primary key,
    project_id bigint not null references public.projects(id) on delete cascade,
    file_name text not null,
    storage_path text not null unique,
    file_type text,
    file_size bigint not null default 0 check (file_size >= 0),
    uploaded_by bigint references public.users(id) on delete set null,
    created_at timestamptz not null default now()
);

create index if not exists project_files_project_created_idx
    on public.project_files (project_id, created_at desc);

create index if not exists project_files_uploaded_by_idx
    on public.project_files (uploaded_by);

-- The application server uses the Supabase service key.  Keep this metadata
-- inaccessible to direct browser clients; all file access goes through the
-- authenticated project endpoints, which enforce project membership.
alter table public.project_files enable row level security;

revoke all on table public.project_files from anon, authenticated;

-- New uploads are stored in the private `project-files` bucket. The server
-- creates it on first use. Existing legacy files in `task-files/projects/*`
-- remain readable through the compatibility endpoint and are not touched.
